INSERT INTO foods (name, description, url_image, price, category_id, cooking_time)
-- main food ---------------------------------------------------------------------
-- burger url
VALUES ('Big Burger', 'A super yummy beef patty with fresh veggies. The bun is nice and fluffy and has seeds on it. You can also put mustard if you want.', 'https://assets.epicurious.com/photos/556dd2d1d8348b711704fee9/6:4/w_620%2Ch_413/56389604_insanity-burger_6x4.jpg', 1300, 1, 15),
('Chicken Delish','This spicy, saucy chicken is cooked to perfection in our house-made awesome sauce. Topped with blue cheeze and melty goodness! ','https://i.pinimg.com/474x/27/5a/13/275a13af2d65a6ecbe0bf9771f408f22.jpg', 1495, 2, 25),
('Gooey Sandwich','This delicious, gooey chicken sandwich is sure to delight! Stacked with chicken, cheese and veggies on a house-made bun! Dig in!','https://cd-img.s3-us-west-2.amazonaws.com/r/248/d/bd800960-4d40-11e7-a695-1b60a8a2ea19.png', 1595, 1, 25),
('I can haz Pizza','A Cheeseburger Pizza! You can share it with your cat if you want to, but I bet you will want it all for yourself! Ground beef, cheese!','https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Farrukh_Aziz_Ansari/Pizza_Margherita_400.jpg', 1749, 1, 15),
('Bubble Tea','A creamy, sweet, bubbly delight! Full of those chewy, satisfying, delightful little mouthfuls with plenty of sugar and either milk or coconut milk.','https://guestlist.net/uploads/articles/9/504_medium.jpg', 799, 3, 10),
('Pizza Supreme','Another delicious type of Pizza! This one has lots of toppings like green things, red things and orange things! So nice and awesome!','https://cdn.kiwilimon.com/recetaimagen/2728/th5-640x426-14624.jpg', 1749, 2, 25),
('Poutine','A super, duper canadian classic! Russet potato fries topped with lots of gravy and cheese. It’s big enough to share, but we don’t recommend.','https://smartcdn.prod.postmedia.digital/torontosun/wp-content/uploads/2021/05/POUTINEGettyImages-682363978-e1621971929295.jpg?quality=90&strip=all&w=400', 1095, 1, 15),
('Nachos','What’s better than a big plate of Nachos? Piled high with cheese, green onions, olives, jalapenos, black beans, corn and served with salsa','https://www.craftycookingbyanna.com/wp-content/uploads/2017/04/Matzah_Nachos_thumb.jpg', 1249, 1, 20),
('Tacos','They come with a Mariachi Band! No, just kidding, they are pretty delicious though. Piled high with whatever toppings you want and home made hot sauce!','https://media.self.com/photos/58dd72dddc111c1e3cc619c9/master/w_400%2Cc_limit/Blackened-Fish-Tacos-with-Avocado-Cilantro-Sauce.jpg', 1395, 2, 15),
('Beefsteak Sandwich', 'The best darn sammich you will ever have! Piled high with beef steak and fresh veggies, you can’t go wrong with this one!', 'https://illawarrameatco.files.wordpress.com/2015/08/tasty-beef-burgers_1332736100.jpg', 1295, 2, 25)
