-- Drop and recreate Users table (Example)
CREATE DATABASE midterm;
\c midterm

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  payment_id INTEGER NOT NULL REFERENCES payment(id) ON DELETE CASCADE
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  order_items TIMESTAMP DEFAULT now(),
  complete_time TIMESTAMP DEFAULT now(),
  isPaid BOOLEAN DEFAULT false,
  isReady BOOLEAN DEFAULT false
);

CREATE TABLE order_items (
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
);

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  quantity SMALLINT NOT NULL,
  is_ready BOOLEAN DEFAULT false,
  special_instructions TEXT,
  cooking_time INTEGER NOT NULL,
  url_image VARCHAR(255) NOT NULL,
  price INTEGER  NOT NULL DEFAULT 0,
  type VARCHAR(255) NOT NULL
);
